### ISSUE TITLE
CollectionDB problem

### ISSUE THREAD

**Issue by isikriza** [isikriza/tomahawk-android#3]
Cihazımıza yeni bir şarkı eklendiğinde ya da silindiğinde, uygulama da güncellemek için tüm şarkıları siliyor ve yeniden yaratıp yüklüyor. Silinme olayı org.tomahawk.libtomahawk.collection.UserCollection. dosyasının içinde processMediaWrappers metodunda gerçekleşiyor.
Bu metod wipe() metodunu çağırıyor ve UserCollection verileri oluşturmak için parçaları işliyor.
ProcessMediaWrappers metodu GetMediaItemsRunnable sınıfının içinde run() metodu ile çağırılıyor.
Bu sorunu aşmak için uygun bir veri yapısı tasarlanabilir ve cihazdaki bir veya daha fazla şarkının silinmesi veya yüklenmesi durumunda hepsini yeniden oluşturmak yerine bu veri yapısı ile kıyaslanarak şarkı yüklenebilir veya silinebilir.

**Comment by cagdasgerede** [comment]
Bu problemin bir videosunu ekler misin buraya?

**Comment by isikriza** [comment]
Hocam bu sorunu ayrıntılı bir şekilde inceledikten sonra koşulları sağlamadığını fark ettim. Yeni bir sorun paylaştım onu değerlendirirseniz çok sevinirim. Link: https://github.com/isikriza/tomahawk-android/issues/6
